// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"
	model "scheduler/internal/model"

	gomock "github.com/golang/mock/gomock"
)

// MockIScheduleService is a mock of IScheduleService interface.
type MockIScheduleService struct {
	ctrl     *gomock.Controller
	recorder *MockIScheduleServiceMockRecorder
}

// MockIScheduleServiceMockRecorder is the mock recorder for MockIScheduleService.
type MockIScheduleServiceMockRecorder struct {
	mock *MockIScheduleService
}

// NewMockIScheduleService creates a new mock instance.
func NewMockIScheduleService(ctrl *gomock.Controller) *MockIScheduleService {
	mock := &MockIScheduleService{ctrl: ctrl}
	mock.recorder = &MockIScheduleServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIScheduleService) EXPECT() *MockIScheduleServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m_2 *MockIScheduleService) Create(m model.ScheduleEvent) (model.ScheduleEvent, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Create", m)
	ret0, _ := ret[0].(model.ScheduleEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIScheduleServiceMockRecorder) Create(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIScheduleService)(nil).Create), m)
}

// Delete mocks base method.
func (m *MockIScheduleService) Delete(ID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIScheduleServiceMockRecorder) Delete(ID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIScheduleService)(nil).Delete), ID)
}

// List mocks base method.
func (m *MockIScheduleService) List(params map[string]string) ([]model.ScheduleEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", params)
	ret0, _ := ret[0].([]model.ScheduleEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIScheduleServiceMockRecorder) List(params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIScheduleService)(nil).List), params)
}

// Show mocks base method.
func (m *MockIScheduleService) Show(ID int) (model.ScheduleEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Show", ID)
	ret0, _ := ret[0].(model.ScheduleEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Show indicates an expected call of Show.
func (mr *MockIScheduleServiceMockRecorder) Show(ID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Show", reflect.TypeOf((*MockIScheduleService)(nil).Show), ID)
}

// Update mocks base method.
func (m_2 *MockIScheduleService) Update(ID int, m model.ScheduleEvent) (model.ScheduleEvent, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Update", ID, m)
	ret0, _ := ret[0].(model.ScheduleEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockIScheduleServiceMockRecorder) Update(ID, m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIScheduleService)(nil).Update), ID, m)
}
